#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Dec 09 18:18:22 EET 2024
# SW Build 4126759 on Thu Feb  8 23:52:05 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Top_Level_Test_behav -key {Behavioral:sim_1:Functional:Top_Level_Test} -tclbatch Top_Level_Test.tcl -view /home/edvinest/University/Architektura/proc_terv/Top_Level_Test_behav.wcfg -log simulate.log"
xsim Top_Level_Test_behav -key {Behavioral:sim_1:Functional:Top_Level_Test} -tclbatch Top_Level_Test.tcl -view /home/edvinest/University/Architektura/proc_terv/Top_Level_Test_behav.wcfg -log simulate.log

